[[pages]]
path = "WebML-app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_Predict.py"
name = "Predict"
icon = " ğŸ”®"

[[pages]]
path = "pages/2_Model-data.py"
name = "Model-data"
icon = "ğŸ“Š"

[[pages]]
path = "pages/GPT Clone.py"
name = "GPT Clone"
icon = "ğŸ’¬"
